# Generated by Django 4.1.3 on 2022-12-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_register', models.CharField(max_length=10)),
                ('Nama', models.CharField(max_length=30)),
                ('Alamat', models.TextField()),
                ('Keterangan', models.TextField()),
            ],
        ),
    ]
